### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by ghost** [thetechnick/hcloud-ansible#12]
Thanks for your great work, @thetechnick.

Is it possible also providing artifacts for mac os?

**Comment by thetechnick** [comment]
Hi @perunb,
sure, no big deal.

I have no Mac OS machine, so here is a cross compile of the current `v1.3.0`.
If you can confirm it is working I will add a mac os version for all future releases.

[hcloud-ansible_v0.3.1_darwin_amd64.zip](https://github.com/thetechnick/hcloud-ansible/files/1934831/hcloud-ansible_v0.3.1_darwin_amd64.zip)

**Comment by ghost** [comment]
Works like a charm! :)
It would be great if you also can provide mac artifacts for all future releases.
Thanks for your fast reply
