### ISSUE TITLE
state: restarted should start the server if it isn't running

### ISSUE THREAD

**Issue by varunchopra** [thetechnick/hcloud-ansible#16]
If I set `state: restarted`, it should boot off > boot on, or simply boot on, depending on it's current state.

**Comment by thetechnick** [comment]
Hi @chopraaa,
when the `state: restarted` is specified, the module always issues a soft-reboot using ACPI:
https://docs.hetzner.cloud/#resources-server-actions-post-1

Can you elaborate, why this does not work for you?

**Comment by varunchopra** [comment]
Soft-reboot is issued to the server itself which requires the server to be running.

I'd like `restarted` to work for stopped servers as well, as it's common practice in the ansible community. (see: service module, for instance) Also, if the server doesn't respond to a soft reboot it should trigger a power off > power on for a hard reboot.

**Comment by thetechnick** [comment]
Implemented in v0.3.2
