### ISSUE TITLE
hcloud_server force parameter for implicit destruction of servers

### ISSUE THREAD

**Issue by thelegy** [thetechnick/hcloud-ansible#6]
As an enhancement I would like to have some kind of force-flag.

If you have a server already up and running as a cx11 for example and you run your hcloud_server module against it but you change the servertype to something else, let's say cx21, the whole server will be taken down and recreated with a complete loss of all data. This seems quite risky to me.

I would like to have a 'force' flag that would need to be set for all actions with potential loss of data. Without this flag set all actions that destroy the server would need to fail. This would make for a much safer use of your module.

For consitency reasons I would also require the force flag for the `state=absent` but that is not critical as `state=absent` states the destruction of the server clearly, but for all cases where it happens implicitly I believe it is quite importent.

**Comment by thetechnick** [comment]
This issue is now covered by the resource protection flags in the Hetzner Cloud API and Console.
https://twitter.com/Hetzner_Online/status/984436514175188993?s=20

I will still add documentation about implicit deletion and point to the Hetzner Cloud Feature.
